// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVU7Nj1ukT2AuVpku8OrAM9bTtp9EFhNY',
    appId: '1:779392931597:web:f4ce87edf9c4ccd1f20244',
    messagingSenderId: '779392931597',
    projectId: 'task-cpf-f70d6',
    authDomain: 'task-cpf-f70d6.firebaseapp.com',
    storageBucket: 'task-cpf-f70d6.firebasestorage.app',
    measurementId: 'G-S1L8CF993B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-H_it0FBth2BQkFspryKZbt9XCQx4IZ0',
    appId: '1:779392931597:android:b80505288a3bd39ff20244',
    messagingSenderId: '779392931597',
    projectId: 'task-cpf-f70d6',
    storageBucket: 'task-cpf-f70d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgqXpCR-Fy93JrH5oRgwZb3mi_xTJCMlI',
    appId: '1:779392931597:ios:d164a3501d77ba58f20244',
    messagingSenderId: '779392931597',
    projectId: 'task-cpf-f70d6',
    storageBucket: 'task-cpf-f70d6.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgqXpCR-Fy93JrH5oRgwZb3mi_xTJCMlI',
    appId: '1:779392931597:ios:d164a3501d77ba58f20244',
    messagingSenderId: '779392931597',
    projectId: 'task-cpf-f70d6',
    storageBucket: 'task-cpf-f70d6.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVU7Nj1ukT2AuVpku8OrAM9bTtp9EFhNY',
    appId: '1:779392931597:web:35eec1145fd64e22f20244',
    messagingSenderId: '779392931597',
    projectId: 'task-cpf-f70d6',
    authDomain: 'task-cpf-f70d6.firebaseapp.com',
    storageBucket: 'task-cpf-f70d6.firebasestorage.app',
    measurementId: 'G-7K3TWGNM8L',
  );
}
